# Ejercicios de clase Modulo 3


# Numpy avanzado

In [2]:
import numpy as np
import pandas as pd

In [3]:
lista = []
for i in range(2, 40, 2):
        lista.append(i)
        
np.array(lista).shape

(19,)

In [4]:
array_pares = np.array([i for i in range(2, 22, 2)])

In [5]:
array_pares.ndim # una dimension

1

In [6]:
array_pares.size # tamaño, numero de elementos totales


10

In [7]:
array_pares.shape # nro de elementos en cada dimension

(10,)

In [8]:
array_pares.dtype # tipo de datos

dtype('int64')

In [9]:
# crea una lista de 5 pares y otra de 5 impares y utilizar un metodo de np para pasarlo a una matriz de 2x5
# concatenate y reshape
array_pares = np.array([i for i in range(2, 12, 2)])
array_impares = np.array([i for i in range(1, 11, 2)])
todos = np.concatenate((array_pares, array_impares))
nuevo5x2 = todos.reshape(5, 2)
nuevo5x2

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [10]:
"""! pip install plotly
! pip install pillow
! pip install folium
! pip install openpyxl
! pip install requests
"""


'! pip install plotly\n! pip install pillow\n! pip install folium\n! pip install openpyxl\n! pip install requests\n'

In [11]:
lista = ([2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24], [26, 28, 30, 32], [34, 36, 38, 40])
np.array(lista)


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [12]:
np.argmin(lista)


np.int64(0)

In [13]:
np.argmax(lista)

np.int64(19)

In [14]:
np.reshape(lista, newshape = (4, 5))

C:\Users\user\AppData\Local\Temp\ipykernel_17064\3861157553.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(lista, newshape = (4, 5))


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [15]:
nuevo5x2.dtype


dtype('int64')

In [16]:
np.hstack((nuevo5x2, nuevo5x2)) #en horizontal

array([[ 2,  4,  2,  4],
       [ 6,  8,  6,  8],
       [10,  1, 10,  1],
       [ 3,  5,  3,  5],
       [ 7,  9,  7,  9]])

In [17]:
# aplana de dos dimensiones a una dimension
nuevo5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [18]:
np.vstack((nuevo5x2, nuevo5x2)) # en vertical

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9],
       [ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

np.column_stack((array_pares, array_impares))

In [19]:
nuevo5x2.T

array([[ 2,  6, 10,  3,  7],
       [ 4,  8,  1,  5,  9]])

In [20]:
print(array_pares)
indices = np.where(array_pares > 5) #devuelve los indices de los elementos que cumplen con las condiciones
array_pares[indices]

[ 2  4  6  8 10]


array([ 6,  8, 10])

# Introduccion Pandas

In [21]:
# import pandas as pd

In [22]:
print(f"pandas=={pd.__version__}")

pandas==2.2.3


* Cargar un dataframe desde una lista

In [23]:
#Crear Data Frame de 0
df = pd.DataFrame()


In [24]:
lista = list(range(100, 105))
df["nueva columna1"] = lista
df["nueva_columna2"] = lista
# df["total_price"] = df[unit_price"] * df[quantity]]
df

nueva columna1  nueva_columna2
0             100             100
1             101             101
2             102             102
3             103             103
4             104             104

* Cargar una matriz en un dataframe

In [25]:
matriz =[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

In [26]:
pd.DataFrame(matriz, columns = ["col_1", "col_2", "col_3"])

col_1  col_2  col_3
0      1      2      3
1      4      5      6
2      7      8      9

In [27]:
#diccionario = {num : 1 for num, 1}

* Cargar un CSV con pandas

In [28]:
iris = pd.read_csv(filepath_or_buffer="iris.csv")

* Cargar un xls en pandas

In [29]:
pd.read_excel(io="iris.xlsx") #se necesita tener installado el openpyxl (pip install openpyxl)

Largo Sepalo   Ancho Sepalo   Largo Petalo   Ancho Petalo           Clase
0             5.1            3.5            1.4            0.2     Iris-setosa
1             4.9            3.0            1.4            0.2     Iris-setosa
2             4.7            3.2            1.3            0.2     Iris-setosa
3             4.6            3.1            1.5            0.2     Iris-setosa
4             5.0            3.6            1.4            0.2     Iris-setosa
..            ...            ...            ...            ...             ...
145           6.7            3.0            5.2            2.3  Iris-virginica
146           6.3            2.5            5.0            1.9  Iris-virginica
147           6.5            3.0            5.2            2.0  Iris-virginica
148           6.2            3.4            5.4            2.3  Iris-virginica
149           5.9            3.0            5.1            1.8  Iris-virginica

[150 rows x 5 columns]

In [30]:
iris.head() #muestra las 5 primeras filas


Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo        Clase
0           5.1           3.5           1.4           0.2  Iris-setosa
1           4.9           3.0           1.4           0.2  Iris-setosa
2           4.7           3.2           1.3           0.2  Iris-setosa
3           4.6           3.1           1.5           0.2  Iris-setosa
4           5.0           3.6           1.4           0.2  Iris-setosa

In [31]:
iris.tail() # muestra las 5 ultimas filas

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
145           6.7           3.0           5.2           2.3  Iris-virginica
146           6.3           2.5           5.0           1.9  Iris-virginica
147           6.5           3.0           5.2           2.0  Iris-virginica
148           6.2           3.4           5.4           2.3  Iris-virginica
149           5.9           3.0           5.1           1.8  Iris-virginica

In [32]:
iris.tail(10) # muestra las 10 ultimas

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
140           6.7           3.1           5.6           2.4  Iris-virginica
141           6.9           3.1           5.1           2.3  Iris-virginica
142           5.8           2.7           5.1           1.9  Iris-virginica
143           6.8           3.2           5.9           2.3  Iris-virginica
144           6.7           3.3           5.7           2.5  Iris-virginica
145           6.7           3.0           5.2           2.3  Iris-virginica
146           6.3           2.5           5.0           1.9  Iris-virginica
147           6.5           3.0           5.2           2.0  Iris-virginica
148           6.2           3.4           5.4           2.3  Iris-virginica
149           5.9           3.0           5.1           1.8  Iris-virginica

In [33]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Largo Sepalo  150 non-null    float64
 1   Ancho Sepalo  150 non-null    float64
 2   Largo Petalo  150 non-null    float64
 3   Ancho Petalo  150 non-null    float64
 4   Clase         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [34]:
iris.columns

Index(['Largo Sepalo', 'Ancho Sepalo', 'Largo Petalo', 'Ancho Petalo',
       'Clase'],
      dtype='object')

In [35]:
type(iris["Largo Sepalo"].values)

numpy.ndarray

In [36]:
iris["Largo Petalo"]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: Largo Petalo, Length: 150, dtype: float64

In [37]:
iris[["Ancho Petalo", "Ancho Sepalo"]]
df_iris = iris[["Ancho Petalo", "Ancho Sepalo"]].copy() #crea una copia con la que se puede jugar sin afectar al original

In [38]:
iris["Clase"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Clase, Length: 150, dtype: object

In [39]:
iris["Largo Sepalo"][2] # iris[columna][indice fila]
iris["Largo Sepalo"].iat[2] # este es lo mismo que el anterior

np.float64(4.7)

In [40]:
iris.iloc[0]

Largo Sepalo            5.1
Ancho Sepalo            3.5
Largo Petalo            1.4
Ancho Petalo            0.2
Clase           Iris-setosa
Name: 0, dtype: object

In [41]:
iris.iloc[0, 1]

np.float64(3.5)

In [42]:
iris[["Largo Sepalo", "Ancho Sepalo"]].cumsum()

Largo Sepalo  Ancho Sepalo
0             5.1           3.5
1            10.0           6.5
2            14.7           9.7
3            19.3          12.8
4            24.3          16.4
..            ...           ...
145         851.6         446.2
146         857.9         448.7
147         864.4         451.7
148         870.6         455.1
149         876.5         458.1

[150 rows x 2 columns]

In [43]:
iris.iloc[:, -1] # pilla la ultima columna

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Clase, Length: 150, dtype: object

In [44]:
iris.iloc[:, -1].mode() # saca la moda, en este caso dice que son las tres pues de todas hay 50 ocurrencias


0        Iris-setosa
1    Iris-versicolor
2     Iris-virginica
Name: Clase, dtype: object

In [45]:
iris.count()

Largo Sepalo    150
Ancho Sepalo    150
Largo Petalo    150
Ancho Petalo    150
Clase           150
dtype: int64

In [46]:
iris.describe() #hace todos los calculos de cada columna

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo
count    150.000000    150.000000    150.000000    150.000000
mean       5.843333      3.054000      3.758667      1.198667
std        0.828066      0.433594      1.764420      0.763161
min        4.300000      2.000000      1.000000      0.100000
25%        5.100000      2.800000      1.600000      0.300000
50%        5.800000      3.000000      4.350000      1.300000
75%        6.400000      3.300000      5.100000      1.800000
max        7.900000      4.400000      6.900000      2.500000

In [47]:
iris.describe(include='all') # incluye tambien las de tipo texto

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo        Clase
count     150.000000    150.000000    150.000000    150.000000          150
unique           NaN           NaN           NaN           NaN            3
top              NaN           NaN           NaN           NaN  Iris-setosa
freq             NaN           NaN           NaN           NaN           50
mean        5.843333      3.054000      3.758667      1.198667          NaN
std         0.828066      0.433594      1.764420      0.763161          NaN
min         4.300000      2.000000      1.000000      0.100000          NaN
25%         5.100000      2.800000      1.600000      0.300000          NaN
50%         5.800000      3.000000      4.350000      1.300000          NaN
75%         6.400000      3.300000      5.100000      1.800000          NaN
max         7.900000      4.400000      6.900000      2.500000          NaN

In [48]:
# en caso de tener muchas columnas, se puede invertir la matriz de estadisticas
iris.describe(include='all').T

count unique          top freq      mean       std  min  25%  \
Largo Sepalo  150.0    NaN          NaN  NaN  5.843333  0.828066  4.3  5.1   
Ancho Sepalo  150.0    NaN          NaN  NaN     3.054  0.433594  2.0  2.8   
Largo Petalo  150.0    NaN          NaN  NaN  3.758667   1.76442  1.0  1.6   
Ancho Petalo  150.0    NaN          NaN  NaN  1.198667  0.763161  0.1  0.3   
Clase           150      3  Iris-setosa   50       NaN       NaN  NaN  NaN   

               50%  75%  max  
Largo Sepalo   5.8  6.4  7.9  
Ancho Sepalo   3.0  3.3  4.4  
Largo Petalo  4.35  5.1  6.9  
Ancho Petalo   1.3  1.8  2.5  
Clase          NaN  NaN  NaN

In [49]:
iris.sort_values("Largo Sepalo")

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
13            4.3           3.0           1.1           0.1     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
41            4.5           2.3           1.3           0.3     Iris-setosa
..            ...           ...           ...           ...             ...
122           7.7           2.8           6.7           2.0  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
135           7.7           3.0           6.1           2.3  Iris-virginica
131           7.9           3.8           6.4           2.0  Iris-virginica

[150 rows x 5 columns]

In [50]:
iris.sort_values(["Largo Sepalo", "Largo Petalo"]) # no olvidar los corchetes cuando hay mas de un valor


Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
13            4.3           3.0           1.1           0.1     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
41            4.5           2.3           1.3           0.3     Iris-setosa
..            ...           ...           ...           ...             ...
135           7.7           3.0           6.1           2.3  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
122           7.7           2.8           6.7           2.0  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
131           7.9           3.8           6.4           2.0  Iris-virginica

[150 rows x 5 columns]

In [51]:
top_10_iris_largo_sepalo = iris.sort_values("Largo Sepalo", ascending=False)[:10]
top_10_iris_largo_sepalo

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
131           7.9           3.8           6.4           2.0  Iris-virginica
122           7.7           2.8           6.7           2.0  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
135           7.7           3.0           6.1           2.3  Iris-virginica
105           7.6           3.0           6.6           2.1  Iris-virginica
130           7.4           2.8           6.1           1.9  Iris-virginica
107           7.3           2.9           6.3           1.8  Iris-virginica
109           7.2           3.6           6.1           2.5  Iris-virginica
129           7.2           3.0           5.8           1.6  Iris-virginica

In [52]:
# Ordenar por sepalo descendente y dentro por petalo ascendente y muestra los 20 primeros
iris.sort_values(["Largo Sepalo", "Largo Petalo"], ascending=[False, True]).head(20)

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo            Clase
131           7.9           3.8           6.4           2.0   Iris-virginica
135           7.7           3.0           6.1           2.3   Iris-virginica
117           7.7           3.8           6.7           2.2   Iris-virginica
122           7.7           2.8           6.7           2.0   Iris-virginica
118           7.7           2.6           6.9           2.3   Iris-virginica
105           7.6           3.0           6.6           2.1   Iris-virginica
130           7.4           2.8           6.1           1.9   Iris-virginica
107           7.3           2.9           6.3           1.8   Iris-virginica
129           7.2           3.0           5.8           1.6   Iris-virginica
125           7.2           3.2           6.0           1.8   Iris-virginica
109           7.2           3.6           6.1           2.5   Iris-virginica
102           7.1           3.0           5.9           2.1   Iris-virginica
50            7.0           3.2           4.7           1.4  Iris-versicolor
52            6.9           3.1           4.9           1.5  Iris-versicolor
141           6.9           3.1           5.1           2.3   Iris-virginica
139           6.9           3.1           5.4           2.1   Iris-virginica
120           6.9           3.2           5.7           2.3   Iris-virginica
76            6.8           2.8           4.8           1.4  Iris-versicolor
112           6.8           3.0           5.5           2.1   Iris-virginica
143           6.8           3.2           5.9           2.3   Iris-virginica

In [53]:
iris["Clase"].nunique() #numero de datos unicos en una columna

3

In [54]:
iris["Clase"].value_counts() #numero de valores unicos en una columna, se utiliza para saber si hay desbalanceo de clases

Clase
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [55]:
iris["Clase"].value_counts(normalize= True) #muestra el porcentaje  que representa cada valor

Clase
Iris-setosa        0.333333
Iris-versicolor    0.333333
Iris-virginica     0.333333
Name: proportion, dtype: float64

In [56]:
iris.drop[2] #borra la fila 2
iris.drop[2, axis = 1] # borra columna 2 , las columnas empiezan en 0

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (663546507.py, line 2)

# 26-12-2024
* Pandas avanzados


In [63]:
df1 = pd.read_csv("titanic_1.csv")
df2 = pd.read_csv("titanic_2.csv")
df3 = pd.read_csv("titanic.csv")

In [58]:
df1.head()

PassengerId                                               Name     Sex  \
0            1                            Braund, Mr. Owen Harris    male   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2            3                             Heikkinen, Miss. Laina  female   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4            5                           Allen, Mr. William Henry    male   

    Age  
0  22.0  
1  38.0  
2  26.0  
3  35.0  
4  35.0

In [60]:
df2.head()


PassengerId  Survived  Pclass            Ticket     Fare
0            1         0       3         A/5 21171   7.2500
1            2         1       1          PC 17599  71.2833
2            3         1       3  STON/O2. 3101282   7.9250
3            4         1       1            113803  53.1000
4            5         0       3            373450   8.0500

In [61]:
df1["Age"] > 18 #serie

0       True
1       True
2       True
3       True
4       True
       ...  
886     True
887     True
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

In [62]:
df1.info() #hay presencia de nulos en Age


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Name         891 non-null    object 
 2   Sex          891 non-null    object 
 3   Age          714 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 28.0+ KB


In [65]:
df3.head()


PassengerId                                               Name     Sex  \
0            1                            Braund, Mr. Owen Harris    male   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2            3                             Heikkinen, Miss. Laina  female   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4            5                           Allen, Mr. William Henry    male   

    Age  Survived  Pclass            Ticket     Fare  
0  22.0         0       3         A/5 21171   7.2500  
1  38.0         1       1          PC 17599  71.2833  
2  26.0         1       3  STON/O2. 3101282   7.9250  
3  35.0         1       1            113803  53.1000  
4  35.0         0       3            373450   8.0500

In [ ]:
#Ejercicio 1
df3.info()

In [70]:
#Ejercicio 2
#Transformar solo una columna
df3["Sex"] = df3["Sex"].astype("category")
df3["Sex"]

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: category
Categories (2, object): ['female', 'male']

In [75]:
#transformar varias columnas a la vez
df3[["Sex", "Name", "Ticket"]] = df3[["Sex", "Name", "Ticket"]].astype("category")
df3.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   PassengerId  891 non-null    int64   
 1   Name         891 non-null    category
 2   Sex          891 non-null    category
 3   Age          714 non-null    float64 
 4   Survived     891 non-null    int64   
 5   Pclass       891 non-null    int64   
 6   Ticket       891 non-null    category
 7   Fare         891 non-null    float64 
dtypes: category(3), float64(2), int64(3)
memory usage: 100.1 KB


In [79]:
#Ejercicio 3
#filtro
df3["Sex"] == "male"

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool

In [80]:
# obtener daos filtrados
df3_male = df3[df3["Sex"] == "male"]
df3_male

PassengerId                            Name   Sex   Age  Survived  \
0              1         Braund, Mr. Owen Harris  male  22.0         0   
4              5        Allen, Mr. William Henry  male  35.0         0   
5              6                Moran, Mr. James  male   NaN         0   
6              7         McCarthy, Mr. Timothy J  male  54.0         0   
7              8  Palsson, Master. Gosta Leonard  male   2.0         0   
..           ...                             ...   ...   ...       ...   
883          884   Banfield, Mr. Frederick James  male  28.0         0   
884          885          Sutehall, Mr. Henry Jr  male  25.0         0   
886          887           Montvila, Rev. Juozas  male  27.0         0   
889          890           Behr, Mr. Karl Howell  male  26.0         1   
890          891             Dooley, Mr. Patrick  male  32.0         0   

     Pclass            Ticket     Fare  
0         3         A/5 21171   7.2500  
4         3            373450   8.0500  
5         3            330877   8.4583  
6         1             17463  51.8625  
7         3            349909  21.0750  
..      ...               ...      ...  
883       2  C.A./SOTON 34068  10.5000  
884       3   SOTON/OQ 392076   7.0500  
886       2            211536  13.0000  
889       1            111369  30.0000  
890       3            370376   7.7500  

[577 rows x 8 columns]

In [81]:
#Ejercicio 4
df3[(df3["Pclass"] == 1) | (df3["Pclass"] ==2)]

PassengerId                                               Name     Sex  \
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
6              7                            McCarthy, Mr. Timothy J    male   
9             10                Nasser, Mrs. Nicholas (Adele Achem)  female   
11            12                           Bonnell, Miss. Elizabeth  female   
..           ...                                                ...     ...   
880          881       Shelley, Mrs. William (Imanita Parrish Hall)  female   
883          884                      Banfield, Mr. Frederick James    male   
886          887                              Montvila, Rev. Juozas    male   
887          888                       Graham, Miss. Margaret Edith  female   
889          890                              Behr, Mr. Karl Howell    male   

      Age  Survived  Pclass            Ticket     Fare  
1    38.0         1       1          PC 17599  71.2833  
3    35.0         1       1            113803  53.1000  
6    54.0         0       1             17463  51.8625  
9    14.0         1       2            237736  30.0708  
11   58.0         1       1            113783  26.5500  
..    ...       ...     ...               ...      ...  
880  25.0         1       2            230433  26.0000  
883  28.0         0       2  C.A./SOTON 34068  10.5000  
886  27.0         0       2            211536  13.0000  
887  19.0         1       1            112053  30.0000  
889  26.0         1       1            111369  30.0000  

[400 rows x 8 columns]

In [82]:
df3_clas = df2[df3["Pclass"].isin([1, 2])]
df3_clas

PassengerId  Survived  Pclass            Ticket     Fare
1              2         1       1          PC 17599  71.2833
3              4         1       1            113803  53.1000
6              7         0       1             17463  51.8625
9             10         1       2            237736  30.0708
11            12         1       1            113783  26.5500
..           ...       ...     ...               ...      ...
880          881         1       2            230433  26.0000
883          884         0       2  C.A./SOTON 34068  10.5000
886          887         0       2            211536  13.0000
887          888         1       1            112053  30.0000
889          890         1       1            111369  30.0000

[400 rows x 5 columns]

In [90]:
#Ejercicio 5
df3_clas = df3(df3["Pclass"].isin([1, 3])) & (df3["Age"] < 30)

TypeError: 'DataFrame' object is not callable

In [ ]:
df3[ (df3["Pclass"].isin([1, 3])) & (df3["Age"] < 30) ]

In [84]:
clase_1_3 = df3["Pclass"].isin([1, 3])
menor_30 = df3["Age"] < 30
df3[clase_1_3 & menor_30]

PassengerId                                               Name     Sex  \
0              1                            Braund, Mr. Owen Harris    male   
2              3                             Heikkinen, Miss. Laina  female   
7              8                     Palsson, Master. Gosta Leonard    male   
8              9  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   
10            11                    Sandstrom, Miss. Marguerite Rut  female   
..           ...                                                ...     ...   
877          878                               Petroff, Mr. Nedelio    male   
882          883                       Dahlberg, Miss. Gerda Ulrika  female   
884          885                             Sutehall, Mr. Henry Jr    male   
887          888                       Graham, Miss. Margaret Edith  female   
889          890                              Behr, Mr. Karl Howell    male   

      Age  Survived  Pclass            Ticket     Fare  
0    22.0         0       3         A/5 21171   7.2500  
2    26.0         1       3  STON/O2. 3101282   7.9250  
7     2.0         0       3            349909  21.0750  
8    27.0         1       3            347742  11.1333  
10    4.0         1       3           PP 9549  16.7000  
..    ...       ...     ...               ...      ...  
877  19.0         0       3            349212   7.8958  
882  22.0         0       3              7552  10.5167  
884  25.0         0       3   SOTON/OQ 392076   7.0500  
887  19.0         1       1            112053  30.0000  
889  26.0         1       1            111369  30.0000  

[296 rows x 8 columns]

In [ ]:
#Ejercicio 6
df3[(df3["Age"].between(20, 30))]

PassengerId         Age    Survived      Pclass        Fare
count   245.000000  245.000000  245.000000  245.000000  245.000000
mean    432.624490   25.091837    0.355102    2.424490   27.101665
std     254.982444    3.134410    0.479524    0.757079   42.826678
min       1.000000   20.000000    0.000000    1.000000    0.000000
25%     222.000000   22.000000    0.000000    2.000000    7.895800
50%     404.000000   25.000000    0.000000    3.000000   10.500000
75%     650.000000   28.000000    1.000000    3.000000   26.000000
max     890.000000   30.000000    1.000000    3.000000  263.000000

In [87]:
df3[(df3["Age"].between(20, 30))].describe() #igual al anterior pero agrega estadisticas

PassengerId         Age    Survived      Pclass        Fare
count   245.000000  245.000000  245.000000  245.000000  245.000000
mean    432.624490   25.091837    0.355102    2.424490   27.101665
std     254.982444    3.134410    0.479524    0.757079   42.826678
min       1.000000   20.000000    0.000000    1.000000    0.000000
25%     222.000000   22.000000    0.000000    2.000000    7.895800
50%     404.000000   25.000000    0.000000    3.000000   10.500000
75%     650.000000   28.000000    1.000000    3.000000   26.000000
max     890.000000   30.000000    1.000000    3.000000  263.000000

In [89]:
#Ejericio 7
df3[~df3["Age"].between(25, 50)]

PassengerId                                           Name     Sex   Age  \
0              1                        Braund, Mr. Owen Harris    male  22.0   
5              6                               Moran, Mr. James    male   NaN   
6              7                        McCarthy, Mr. Timothy J    male  54.0   
7              8                 Palsson, Master. Gosta Leonard    male   2.0   
9             10            Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
..           ...                                            ...     ...   ...   
878          879                             Laleff, Mr. Kristo    male   NaN   
879          880  Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0   
882          883                   Dahlberg, Miss. Gerda Ulrika  female  22.0   
887          888                   Graham, Miss. Margaret Edith  female  19.0   
888          889       Johnston, Miss. Catherine Helen "Carrie"  female   NaN   

     Survived  Pclass      Ticket     Fare  
0           0       3   A/5 21171   7.2500  
5           0       3      330877   8.4583  
6           0       1       17463  51.8625  
7           0       3      349909  21.0750  
9           1       2      237736  30.0708  
..        ...     ...         ...      ...  
878         0       3      349217   7.8958  
879         1       1       11767  83.1583  
882         0       3        7552  10.5167  
887         1       1      112053  30.0000  
888         0       3  W./C. 6607  23.4500  

[519 rows x 8 columns]

In [ ]:
#Ejercicio 8
#Transformar datos

In [91]:
#crear un diccionario con clave male con valor M y clave female con valor F
genre_dict = {"male": "M", "female": "F"}
# pasar el dicionario como parametro de la funcion .map sobre la columna genero
df3["Sex"].map(genre_dict)

0      M
1      F
2      F
3      F
4      M
      ..
886    M
887    F
888    F
889    M
890    M
Name: Sex, Length: 891, dtype: category
Categories (2, object): ['F', 'M']