# Ejercicios de clase Modulo 3


In [22]:
import numpy as np

In [33]:
lista = []
for i in range(2, 40, 2):
        lista.append(i)
        
np.array(lista).shape

(19,)

In [24]:
array_pares = np.array([i for i in range(2, 22, 2)])

In [ ]:
array_pares.ndim # una dimension

In [ ]:
array_pares.size # tamaño, numero de elementos totales


In [ ]:
array_pares.shape # nro de elementos en cada dimension

In [ ]:
array_pares.dtype # tipo de datos

In [54]:
# crea una lista de 5 pares y otra de 5 impares y utilizar un metodo de np para pasarlo a una matriz de 2x5
# concatenate y reshape
array_pares = np.array([i for i in range(2, 12, 2)])
array_impares = np.array([i for i in range(1, 11, 2)])
todos = np.concatenate((array_pares, array_impares))
nuevo5x2 = todos.reshape(5, 2)
nuevo5x2

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [ ]:
"""! pip install plotly
! pip install pillow
! pip install folium
! pip install openpyxl
! pip install requests
"""


In [39]:
lista = ([2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24], [26, 28, 30, 32], [34, 36, 38, 40])
np.array(lista)


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [41]:
np.argmin(lista)


np.int64(0)

In [42]:
np.argmax(lista)

np.int64(19)

In [44]:
np.reshape(lista, newshape = (4, 5))

C:\Users\user\AppData\Local\Temp\ipykernel_11624\3861157553.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(lista, newshape = (4, 5))


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [56]:
nuevo5x2.dtype


dtype('int64')

In [61]:
np.hstack((nuevo5x2, nuevo5x2)) #en horizontal

array([[ 2,  4,  2,  4],
       [ 6,  8,  6,  8],
       [10,  1, 10,  1],
       [ 3,  5,  3,  5],
       [ 7,  9,  7,  9]])

In [59]:
# aplana de dos dimensiones a una dimension
nuevo5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [62]:
np.vstack((nuevo5x2, nuevo5x2)) # en vertical

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9],
       [ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

np.column_stack((array_pares, array_impares))

In [64]:
nuevo5x2.T

array([[ 2,  6, 10,  3,  7],
       [ 4,  8,  1,  5,  9]])

In [68]:
print(array_pares)
indices = np.where(array_pares > 5) #devuelve los indices de los elementos que cumplen con las condiciones
array_pares[indices]

[ 2  4  6  8 10]


array([ 6,  8, 10])

In [77]:
import pandas as pd

In [78]:
print(f"pandas=={pd.__version__}")

pandas==2.2.3


* Cargar un dataframe desde una lista

In [79]:
#Crear Data Frame de 0
df = pd.DataFrame()


In [83]:
lista = list(range(100, 105))
df["nueva columna1"] = lista
df["nueva_columna2"] = lista
# df["total_price"] = df[unit_price"] * df[quantity]]
df

nueva columna  nueva columna1  nueva_columna2
0            100             100             100
1            101             101             101
2            102             102             102
3            103             103             103
4            104             104             104

* Cargar una matriz en un dataframe

In [88]:
matriz =[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

In [89]:
pd.DataFrame(matriz, columns = ["col_1", "col_2", "col_3"])

col_1  col_2  col_3
0      1      2      3
1      4      5      6
2      7      8      9

In [ ]:
diccionario = {num : 1 for num, 1 }

* Cargar un CSV con pandas

In [90]:
pd.read_csv(filepath_or_buffer="iris.csv")

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
0             5.1           3.5           1.4           0.2     Iris-setosa
1             4.9           3.0           1.4           0.2     Iris-setosa
2             4.7           3.2           1.3           0.2     Iris-setosa
3             4.6           3.1           1.5           0.2     Iris-setosa
4             5.0           3.6           1.4           0.2     Iris-setosa
..            ...           ...           ...           ...             ...
145           6.7           3.0           5.2           2.3  Iris-virginica
146           6.3           2.5           5.0           1.9  Iris-virginica
147           6.5           3.0           5.2           2.0  Iris-virginica
148           6.2           3.4           5.4           2.3  Iris-virginica
149           5.9           3.0           5.1           1.8  Iris-virginica

[150 rows x 5 columns]

* Cargar un xls en pandas

In [91]:
pd.read_excel(io="iris.xlsx") #se necesita tener installado el openpyxl (pip install openpyxl)


Largo Sepalo   Ancho Sepalo   Largo Petalo   Ancho Petalo           Clase
0             5.1            3.5            1.4            0.2     Iris-setosa
1             4.9            3.0            1.4            0.2     Iris-setosa
2             4.7            3.2            1.3            0.2     Iris-setosa
3             4.6            3.1            1.5            0.2     Iris-setosa
4             5.0            3.6            1.4            0.2     Iris-setosa
..            ...            ...            ...            ...             ...
145           6.7            3.0            5.2            2.3  Iris-virginica
146           6.3            2.5            5.0            1.9  Iris-virginica
147           6.5            3.0            5.2            2.0  Iris-virginica
148           6.2            3.4            5.4            2.3  Iris-virginica
149           5.9            3.0            5.1            1.8  Iris-virginica

[150 rows x 5 columns]