# Ejercicios de clase Modulo 3


# Numpy avanzado

In [3]:
import numpy as np

In [4]:
lista = []
for i in range(2, 40, 2):
        lista.append(i)
        
np.array(lista).shape

(19,)

In [5]:
array_pares = np.array([i for i in range(2, 22, 2)])

In [6]:
array_pares.ndim # una dimension

1

In [7]:
array_pares.size # tamaño, numero de elementos totales


10

In [8]:
array_pares.shape # nro de elementos en cada dimension

(10,)

In [9]:
array_pares.dtype # tipo de datos

dtype('int64')

In [10]:
# crea una lista de 5 pares y otra de 5 impares y utilizar un metodo de np para pasarlo a una matriz de 2x5
# concatenate y reshape
array_pares = np.array([i for i in range(2, 12, 2)])
array_impares = np.array([i for i in range(1, 11, 2)])
todos = np.concatenate((array_pares, array_impares))
nuevo5x2 = todos.reshape(5, 2)
nuevo5x2

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [11]:
"""! pip install plotly
! pip install pillow
! pip install folium
! pip install openpyxl
! pip install requests
"""


'! pip install plotly\n! pip install pillow\n! pip install folium\n! pip install openpyxl\n! pip install requests\n'

In [12]:
lista = ([2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24], [26, 28, 30, 32], [34, 36, 38, 40])
np.array(lista)


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [13]:
np.argmin(lista)


np.int64(0)

In [14]:
np.argmax(lista)

np.int64(19)

In [15]:
np.reshape(lista, newshape = (4, 5))

C:\Users\user\AppData\Local\Temp\ipykernel_19324\3861157553.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(lista, newshape = (4, 5))


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [16]:
nuevo5x2.dtype


dtype('int64')

In [17]:
np.hstack((nuevo5x2, nuevo5x2)) #en horizontal

array([[ 2,  4,  2,  4],
       [ 6,  8,  6,  8],
       [10,  1, 10,  1],
       [ 3,  5,  3,  5],
       [ 7,  9,  7,  9]])

In [18]:
# aplana de dos dimensiones a una dimension
nuevo5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [19]:
np.vstack((nuevo5x2, nuevo5x2)) # en vertical

array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9],
       [ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

np.column_stack((array_pares, array_impares))

In [20]:
nuevo5x2.T

array([[ 2,  6, 10,  3,  7],
       [ 4,  8,  1,  5,  9]])

In [21]:
print(array_pares)
indices = np.where(array_pares > 5) #devuelve los indices de los elementos que cumplen con las condiciones
array_pares[indices]

[ 2  4  6  8 10]


array([ 6,  8, 10])

# Introduccion Pandas

In [22]:
import pandas as pd

In [23]:
print(f"pandas=={pd.__version__}")

pandas==2.2.3


* Cargar un dataframe desde una lista

In [24]:
#Crear Data Frame de 0
df = pd.DataFrame()


In [25]:
lista = list(range(100, 105))
df["nueva columna1"] = lista
df["nueva_columna2"] = lista
# df["total_price"] = df[unit_price"] * df[quantity]]
df

nueva columna1  nueva_columna2
0             100             100
1             101             101
2             102             102
3             103             103
4             104             104

* Cargar una matriz en un dataframe

In [26]:
matriz =[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

In [27]:
pd.DataFrame(matriz, columns = ["col_1", "col_2", "col_3"])

col_1  col_2  col_3
0      1      2      3
1      4      5      6
2      7      8      9

In [65]:
#diccionario = {num : 1 for num, 1}

SyntaxError: 'in' expected after for-loop variables (2798348183.py, line 1)

* Cargar un CSV con pandas

In [52]:
iris = pd.read_csv(filepath_or_buffer="iris.csv")

* Cargar un xls en pandas

In [ ]:
pd.read_excel(io="iris.xlsx") #se necesita tener installado el openpyxl (pip install openpyxl)

In [ ]:
iris.head() #muestra las 5 primeras filas


In [ ]:
iris.tail() # muestra las 5 ultimas filas

In [ ]:
iris.tail(10) # muestra las 10 ultimas

In [ ]:
iris.info()

In [31]:
iris.columns

Index(['Largo Sepalo', 'Ancho Sepalo', 'Largo Petalo', 'Ancho Petalo',
       'Clase'],
      dtype='object')

In [33]:
type(iris["Largo Sepalo"].values)

numpy.ndarray

In [34]:
iris["Largo Petalo"]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: Largo Petalo, Length: 150, dtype: float64

In [35]:
iris[["Ancho Petalo", "Ancho Sepalo"]]
df_iris = iris[["Ancho Petalo", "Ancho Sepalo"]].copy() #crea una copia con la que se puede jugar sin afectar al original

Ancho Petalo  Ancho Sepalo
0             0.2           3.5
1             0.2           3.0
2             0.2           3.2
3             0.2           3.1
4             0.2           3.6
..            ...           ...
145           2.3           3.0
146           1.9           2.5
147           2.0           3.0
148           2.3           3.4
149           1.8           3.0

[150 rows x 2 columns]

In [36]:
iris["Clase"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Clase, Length: 150, dtype: object

In [ ]:
iris["Largo Sepalo"][2] # iris[columna][indice fila]
iris["Largo Sepalo"].iat[2] # este es lo mismo que el anterior

In [37]:
iris.iloc[0]

Largo Sepalo            5.1
Ancho Sepalo            3.5
Largo Petalo            1.4
Ancho Petalo            0.2
Clase           Iris-setosa
Name: 0, dtype: object

In [40]:
iris.iloc[0, 1]

np.float64(3.5)

In [42]:
iris[["Largo Sepalo", "Ancho Sepalo"]].cumsum()

Largo Sepalo  Ancho Sepalo
0             5.1           3.5
1            10.0           6.5
2            14.7           9.7
3            19.3          12.8
4            24.3          16.4
..            ...           ...
145         851.6         446.2
146         857.9         448.7
147         864.4         451.7
148         870.6         455.1
149         876.5         458.1

[150 rows x 2 columns]

In [43]:
iris.iloc[:, -1] # pilla la ultima columna

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Clase, Length: 150, dtype: object

In [45]:
iris.iloc[:, -1].mode() # saca la moda, en este caso dice que son las tres pues de todas hay 50 ocurrencias


0        Iris-setosa
1    Iris-versicolor
2     Iris-virginica
Name: Clase, dtype: object

In [46]:
iris.count()

Largo Sepalo    150
Ancho Sepalo    150
Largo Petalo    150
Ancho Petalo    150
Clase           150
dtype: int64

In [47]:
iris.describe() #hace todos los calculos de cada columna

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo
count    150.000000    150.000000    150.000000    150.000000
mean       5.843333      3.054000      3.758667      1.198667
std        0.828066      0.433594      1.764420      0.763161
min        4.300000      2.000000      1.000000      0.100000
25%        5.100000      2.800000      1.600000      0.300000
50%        5.800000      3.000000      4.350000      1.300000
75%        6.400000      3.300000      5.100000      1.800000
max        7.900000      4.400000      6.900000      2.500000

In [48]:
iris.describe(include='all') # incluye tambien las de tipo texto

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo        Clase
count     150.000000    150.000000    150.000000    150.000000          150
unique           NaN           NaN           NaN           NaN            3
top              NaN           NaN           NaN           NaN  Iris-setosa
freq             NaN           NaN           NaN           NaN           50
mean        5.843333      3.054000      3.758667      1.198667          NaN
std         0.828066      0.433594      1.764420      0.763161          NaN
min         4.300000      2.000000      1.000000      0.100000          NaN
25%         5.100000      2.800000      1.600000      0.300000          NaN
50%         5.800000      3.000000      4.350000      1.300000          NaN
75%         6.400000      3.300000      5.100000      1.800000          NaN
max         7.900000      4.400000      6.900000      2.500000          NaN

In [49]:
# en caso de tener muchas columnas, se puede invertir la matriz de estadisticas
iris.describe(include='all').T

count unique          top freq      mean       std  min  25%  \
Largo Sepalo  150.0    NaN          NaN  NaN  5.843333  0.828066  4.3  5.1   
Ancho Sepalo  150.0    NaN          NaN  NaN     3.054  0.433594  2.0  2.8   
Largo Petalo  150.0    NaN          NaN  NaN  3.758667   1.76442  1.0  1.6   
Ancho Petalo  150.0    NaN          NaN  NaN  1.198667  0.763161  0.1  0.3   
Clase           150      3  Iris-setosa   50       NaN       NaN  NaN  NaN   

               50%  75%  max  
Largo Sepalo   5.8  6.4  7.9  
Ancho Sepalo   3.0  3.3  4.4  
Largo Petalo  4.35  5.1  6.9  
Ancho Petalo   1.3  1.8  2.5  
Clase          NaN  NaN  NaN

In [56]:
iris.sort_values("Largo Sepalo")

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
13            4.3           3.0           1.1           0.1     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
41            4.5           2.3           1.3           0.3     Iris-setosa
..            ...           ...           ...           ...             ...
122           7.7           2.8           6.7           2.0  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
135           7.7           3.0           6.1           2.3  Iris-virginica
131           7.9           3.8           6.4           2.0  Iris-virginica

[150 rows x 5 columns]

In [57]:
iris.sort_values(["Largo Sepalo", "Largo Petalo"]) # no olvidar los corchetes cuando hay mas de un valor


Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
13            4.3           3.0           1.1           0.1     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
41            4.5           2.3           1.3           0.3     Iris-setosa
..            ...           ...           ...           ...             ...
135           7.7           3.0           6.1           2.3  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
122           7.7           2.8           6.7           2.0  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
131           7.9           3.8           6.4           2.0  Iris-virginica

[150 rows x 5 columns]

In [59]:
top_10_iris_largo_sepalo = iris.sort_values("Largo Sepalo", ascending=False)[:10]
top_10_iris_largo_sepalo

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
131           7.9           3.8           6.4           2.0  Iris-virginica
122           7.7           2.8           6.7           2.0  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
135           7.7           3.0           6.1           2.3  Iris-virginica
105           7.6           3.0           6.6           2.1  Iris-virginica
130           7.4           2.8           6.1           1.9  Iris-virginica
107           7.3           2.9           6.3           1.8  Iris-virginica
109           7.2           3.6           6.1           2.5  Iris-virginica
129           7.2           3.0           5.8           1.6  Iris-virginica

In [60]:
# Ordenar por sepalo descendente y dentro por petalo ascendente y muestra los 20 primeros
iris.sort_values(["Largo Sepalo", "Largo Petalo"], ascending=[False, True]).head(20)

Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo            Clase
131           7.9           3.8           6.4           2.0   Iris-virginica
135           7.7           3.0           6.1           2.3   Iris-virginica
117           7.7           3.8           6.7           2.2   Iris-virginica
122           7.7           2.8           6.7           2.0   Iris-virginica
118           7.7           2.6           6.9           2.3   Iris-virginica
105           7.6           3.0           6.6           2.1   Iris-virginica
130           7.4           2.8           6.1           1.9   Iris-virginica
107           7.3           2.9           6.3           1.8   Iris-virginica
129           7.2           3.0           5.8           1.6   Iris-virginica
125           7.2           3.2           6.0           1.8   Iris-virginica
109           7.2           3.6           6.1           2.5   Iris-virginica
102           7.1           3.0           5.9           2.1   Iris-virginica
50            7.0           3.2           4.7           1.4  Iris-versicolor
52            6.9           3.1           4.9           1.5  Iris-versicolor
141           6.9           3.1           5.1           2.3   Iris-virginica
139           6.9           3.1           5.4           2.1   Iris-virginica
120           6.9           3.2           5.7           2.3   Iris-virginica
76            6.8           2.8           4.8           1.4  Iris-versicolor
112           6.8           3.0           5.5           2.1   Iris-virginica
143           6.8           3.2           5.9           2.3   Iris-virginica

In [62]:
iris["Clase"].nunique() #numero de datos unicos en una columna

3

In [63]:
iris["Clase"].value_counts() #numero de valores unicos en una columna, se utiliza para saber si hay desbalanceo de clases

Clase
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [64]:
iris["Clase"].value_counts(normalize= True) #muestra el porcentaje  que representa cada valor

Clase
Iris-setosa        0.333333
Iris-versicolor    0.333333
Iris-virginica     0.333333
Name: proportion, dtype: float64

In [ ]:
iris.drop[2] #borra la fila 2
iris.drop[2, axis = 1] # borra columna 2 , las columnas empiezan en 0